--- #YAML:1.0
name:               Data-SimplePath
version:            0.005
abstract:           Path-like access to complex data structures
author:
    - Stefan Goebel
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:        0
    Test::NoWarnings:  0
    Test::Warn:        0
requires:
    Storable:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
